piVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: newrelic-synthetics
  namespace: default
subjects:
  - kind: ServiceAccount
    name: newrelic-synthetics
    namespace: default
roleRef:
  kind: Role
  name: newrelic-synthetics
  apiGroup: rbac.authorization.k8s.io
