apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: newrelic-synthetics
  namespace: default
rules:
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch